pool_info:
  default_res: MaxiDAO testnet pool
  name: MaxiDAO testnet pool
  logo_url: https://maxipool.net/logo.png
  description: The testnet pool of MaxiDAO.
pool_fee: 0.05
pool_url: http://test1.maxipool.net
min_difficulty: 20
default_difficulty: 20
default_target_puzzle_hash: txch15eadwu35q65jkt4p3h6mtq38qwyhe0ntzhcecxpah5sgj2yfynfqz4kxqj
pool_fee_puzzle_hash: txch1c67654nr82v2evtfht88lkkzhu4a80dgmk8cnx25mrppcrl4xlaqugv8z6
wallet_fingerprint: 140967488
wallet_id: 1
partial_time_limit: 25
partial_confirmation_delay: 30
scan_start_height: 1000
collect_pool_rewards_interval: 600
confirmation_security_threshold: 6
payment_interval: 600
max_additions_per_transaction: 400
number_of_partials_target: 30
